title:            MPK Analytics
description:      Transforming Data Into Insights Through the Power of R
logo:             site-logo.png
disqus_shortname: mpkanalytics

#Comment out url when working locally to resolve base urls correctly
#url:              http://mpkanalytics.github.io
url:               www.mpkanalytics.com

# Owner/author information
owner:
  name:           Mario Pineda
  avatar:         bio-photo.jpg
  email:          mpineda@mpkanalytics.com
  
  # Social networking links used in footer. Update and remove as you like.
  twitter:        "mpkanalytics"
  facebook:       "mpkanalytics"
  github:         "mpkanalytics"
  linkedin:       "mpkanalytics"
  # instagram:      "mmistakes"
  # tumblr:         "mademistakes"
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    "https://plus.google.com/100929512605522684422"

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-2011187-2
google_verify:      UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        D81F4C18A6CB3018F64D7C827D953DFD   

# Links to include in top navigation
# For external links add external: true
links:
  - title: R Consulting
    url: /consulting
  - title: R Solutions
    url: /solutions
  - title: About Us
    url: /about
  - title: Blog
    url: /blog
  - title: Contact Us
    url: /contact    

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Edmonton
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
#permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "so-simple-theme.sublime-project", "so-simple-theme.sublime-workspace"]