#!/bin/sh

if [ $# == 0 ]
then
	echo "Missing commit message - exiting!"
	exit
fi

echo "Committing..."
git add . -A
git commit -m "$1"


echo "Build site..."
jekyll build

echo "Moving portfolio into place..."
cp _site/portfolio/index.html portfolio/

echo "Synching portfolio folder..."
rsync -avz --exclude '*DS_Store' --delete portfolio mpineda@gpu.srv.ualberta.ca:~/public_html